
gem 'bd_pod_extentions'

require 'bd_pod_extentions'
install! 'cocoapods', :warn_for_multiple_pod_sources => false,:deterministic_uuids => false

# 用于开启Pods的源码与二进制快速转化服务
plugin 'cocoapods-bytedance-transform'
# 用于开启依赖解析加速的服务，传true表示使用，false表示不使用
bytedanceAnalyzeSpeed(true)
bd_use_app("thirdParty","public","toutiao", "fProject")

#全部使用源码
#bd_use_source!

#全部使用二进制
bd_use_binary!

platform :ios, '9.0'

inhibit_all_warnings!

# F100 业务线库
def fhPods
    
    pod 'FHHouseBase' , :path => '../Bundles/ios_house_base', :inhibit_warnings => false # :git => 'git@code.byted.org:fproject/ios_house_base.git' ,:branch => 'feature/develop' #
    #    pod 'FHHouseRent' , :path => '../Bundles/ios_house_rent' #:git => 'git@code.byted.org:fproject/ios_house_rent.git' ,:branch => 'feature/develop' #
    pod 'FHMapSearch' , :path => '../Bundles/ios_map_search', :inhibit_warnings => false # :git => 'git@code.byted.org:fproject/ios_map_search.git' ,:branch => 'feature/develop' #
    pod 'FHHouseHome' , :path => '../Bundles/ios_house_home', :inhibit_warnings => false # :git => 'git@code.byted.org:fproject/ios_house_home.git' ,:branch => 'feature/develop' #
    pod 'FHHouseDetail' , :path => '../Bundles/ios_house_detail', :inhibit_warnings => false # :git => 'git@code.byted.org:fproject/ios_house_detail.git' , :branch => 'feature/develop'
    pod 'FHHouseMessage' , :path => '../Bundles/ios_house_message', :inhibit_warnings => false # :git => 'git@code.byted.org:fproject/ios_house_message.git' , :branch => 'feature/develop'
    pod 'FHHouseList' , :path => '../Bundles/ios_house_list', :inhibit_warnings => false # :git => 'git@code.byted.org:fproject/ios_house_list.git' , :branch => 'feature/develop'
    pod 'FHHouseFind' , :path => '../Bundles/ios_house_find', :inhibit_warnings => false
    pod 'FHHouseMine' , :path => '../Bundles/ios_house_mine', :inhibit_warnings => false
    pod 'FHHouseEpidemicSituation', :path => '../Bundles/ios_house_esituation', :inhibit_warnings => false
    pod 'FHHouseRealtorDetail', :path => '../Bundles/ios_house_realtordetail', :inhibit_warnings => false
    pod 'FHHouseUGC' , :path => '../Bundles/ios_house_ugc', :inhibit_warnings => false
    pod 'FHHouseTrend' , :path => '../Bundles/ios_house_trend', :inhibit_warnings => false
    pod 'FHCHousePush' , :path => '../Bundles/FHCHousePush', :inhibit_warnings => false#,:git => 'git@code.byted.org:fproject/FHCHousePush.git' , :branch => 'feature/develop'
    #    pod 'FHCHousePush' , :git => 'git@code.byted.org:fproject/FHCHousePush.git' , :branch => 'feature/develop'
    
    pod 'FHWebView', :path => '../AKPlugins/FHWebView', :inhibit_warnings => false
    pod 'FHLynxKit' , :path => '../Bundles/ios_common_lynx', :inhibit_warnings => false

#    pod 'ios_house_filter' , :git => 'git@code.byted.org:fproject/ios_house_filter.git', :commit => '60e9866a118874a07ca697cfbc4155bfa6b3d72c' #:branch => 'feature/develop'filter-triangle-open-highlighted
    pod 'ios_house_filter' , '1.0.2.2-bugfix', :inhibit_warnings => false


    pod 'FHCommonUI','0.9.0.4', :inhibit_warnings => false
#    pod 'FHCommonUI',:path => '../../ios_common_ui/'
#    pod 'FHCommonUI', :git => 'git@code.byted.org:fproject/ios_common_ui.git', :commit => 'df694e57a8c75b599b241fbd5114c55c767bf0a5'


    pod 'FHPopupViewCenter', '0.0.2-rc.7', :inhibit_warnings => false, :subspecs => [
    'Core',
    'DelegateForC'
    ]
    #    pod 'FHPopupViewCenter', :path => '../../../FHPopupViewCenter', :subspecs => [
    #    'Core',
    #    'DelegateForC'
    #    ]
    # pod 'FHPopupViewCenter', :git => 'git@code.byted.org:fproject/FHPopupViewCenter.git', :commit => '819997a3afbc7eb3e1eaf2b0d8cc3ecb488b71c1', :subspecs => [
    # 'Core',
    # 'DelegateForC'
    #]
    
#   pod 'ios_house_im' ,'0.2.15'
#   pod 'ios_house_im' , :path => '../../../im/1'
    pod 'ios_house_im' , :git => 'git@code.byted.org:fproject/ios_house_im.git' , :commit => 'dafc1a9014724e3b47612a01529757dfc00167e9'

end

def appDevelopPods
    
    pod 'TTAD', :path => '../TTBundles/ios_tt_ad'
    pod 'TTAiKan', :path => '../TTBundles/ios_tt_aikan'
    pod 'TTAppRuntime', :path => '../TTBundles/ios_tt_appruntime'
    pod 'TTArticle', :path => '../TTBundles/ios_tt_article'
    pod 'TTArticleBase', :path => '../TTBundles/ios_tt_articlebase'
    pod 'TTFeedTab', :path => '../TTBundles/ios_tt_feedtab'
    pod 'TTGallery', :path => '../TTBundles/ios_tt_gallery'
    pod 'TTHTSVideo', :path => '../TTBundles/ios_tt_htsvideo'
    pod 'TTSearch', :path => '../TTBundles/ios_tt_search'
    pod 'TTService', :path => '../TTBundles/ios_tt_service'
    pod 'TTUserProfile', :path => '../TTBundles/ios_tt_userprofile'
    pod 'TTArticleVideo', :path => '../TTBundles/ios_tt_article_video'
    # 老的头条监控库添加
    pod 'TTMonitor', :path => '../AKPlugins/TTMonitor'
    #-----头条旧业务兼容库-----#
    pod 'TTCompatibleModule', :path => '../AKPlugins/TTCompatibleModule'
    #-----问答业务库-----#
    pod 'AKWDPlugin', :path => '../AKPlugins/AKWDPlugin'
    #-----平台基础库-----#
    pod 'TTPlatformBaseLib'  , :path => '../AKPlugins/TTPlatformBaseLib'
    #-----评论业务库-----#
    pod 'AKCommentPlugin', :path => '../AKPlugins/AKCommentPlugin'
    #-----头条图片滑动浏览器----
    pod 'TTPhotoScrollVC', :path => '../AKPlugins/TTPhotoScrollVC'
    #-----UI库----
    #-----账号登录UI库-----
    pod 'TTAccountLogin', :path => '../AKPlugins/AKAccountLogin'
    #-----账号的业务库----
    pod 'TTNewsAccountBusiness', :path => '../AKPlugins/TTNewsAccountBusiness'
    pod 'yoga', :path => '../ReactCommon/yoga'
    pod 'BDTArticle', :path => '../AKPlugins/BDTArticle' #'0.2.3'
    pod 'BDTExploreOrderedData', :path => '../AKPlugins/BDTExploreOrderedData' #'0.1.7'
    pod 'BDTBasePlayer' , :path => '../AKPlugins/BDTBasePlayer'
    pod 'BDTSharedHeaders', :path => '../Vendor/BDTSharedHeaders'
    #----- 新分享库 -----
    pod 'AKShareServicePlugin', :path => '../AKPlugins/AKShareServicePlugin'
    
    pod 'TTShare' , :path => '../AKPlugins/TTShare'  , :subspecs => [  # '0.3.3'
    'TTShareBusiness/TTShareWeChatBusiness',
    'TTShareBusiness/TTShareQQBusiness',
    'TTShareBusiness/TTShareCopyBusiness',
    'TTShareBusiness/TTActivity',
    'TTShareBasic/TTWeChatShare',
    'TTShareBasic/TTQQShare'
    ]
    #----头条webview库-----
    pod 'AKWebViewBundlePlugin', :path => '../AKPlugins/AKWebViewBundlePlugin'
    #-----头条号---
    pod 'TTAdModule', :path => '../AKPlugins/TTAdModule' #'0.1.25'
    #-----朋友关系-----
    pod 'TTFriendRelation', :path => '../AKPlugins/TTFriendRelation'
    #----点赞按钮-----
    pod 'TTDiggButton', :path => '../AKPlugins/AKDiggButton'
    #-----平台化UIModel库-----
    pod 'TTPlatformUIModel', :path => '../AKPlugins/AKPlatformUIModel'
    #-----音频相关库---
    pod_binary 'TTAudio', '0.1.6'
    
    #----弹窗互斥---
    pod 'TTDialogDirector', '0.1.4' , :subspecs => [
    'Core',
    'PhotoLibrary',
    'Microphone',
    'Camera',
    'UserNotification'
#    'Contacts',
    #    'Location'
    ]
    #-----视频业务库-----#
    pod 'TTVPlayerPod', :path => '../AKPlugins/TTVPlayer'
    #-----小视频-----
    pod 'HTSVideoPlay', :path => '../Vendor/ShortVideo'
    
    #-----UGC-----
    #    pod 'TTUGCFeature', :path => '../Vendor/TTUGCFeature', :inhibit_warnings => false
    pod 'TTUGCFoundation', :path => '../Vendor/TTUGCFoundation'
    pod 'TTPostBase', :path => '../AKPlugins/TTPostBase'

    
end

def appPods
    #-----头条图片/视频选择器-----
    pod 'TTImagePicker', '7.5.5.12'
    pod 'TTImagePickerBase', '1.0.4'
  
    pod_binary 'SecGuard' , '0.8.16.9'
    
    pod_binary 'IESGeckoKit', '0.4.0'
    pod_binary 'IESWebKit', '0.2.0-rc.3'
    
    pod_binary 'TTVideoService', '0.1.71'
    pod_binary 'TTVideoService/TTBusinessService', '0.1.71'

    pod_binary 'TSVToolkit', '0.1.2'
    pod_binary 'lottie-ios', '2.1.5'

    pod 'TTKitchen','3.0.1',:subspecs => [
    'Core',
    'SettingsSyncer'
    ]
    pod 'TTKitchenExtension','1.0.14'
    
    pod_binary 'TTPerformanceHelper', '0.1.1', :subspecs => [
    'TTThreadSafeContainer',
    'TTUserDefaultHelper'
    ]
    
    #-----UGC Other-----
    pod 'TTSettingsManager','0.4.16'
    pod 'TTLocationManager','1.2.4'
    
    pod_binary 'BDUGLocationKit', '1.5.1',:subspecs => [
    'Core',
    'Network',
    'Location',
    'Log',
    'Foundation',
    'Adapter',
    'DataCollection',
    'AmapLocation'
    ]
    
    pod 'BDUGSettingsInterface' , '1.1.0'
    pod 'BDUGKit' , '1.3.3'
    
    pod_binary 'Gaia','3.1.0-rc.5'
    pod_binary 'TTGaiaExtension','0.4.7'
    pod 'BDAssert','2.0.0',:subspecs => [
    'Core'
    ]
    pod_binary 'BDTFactoryConfigurator', '0.1.0'

    pod_binary 'TencentQQSDK','1.0.0' #QQ SDK降级 iOS13有问题
    pod        'WechatSDK','0.3.0'

    #-----免流量统计-----
    pod_binary 'TTFlowStatisticsManager', '0.2.1'

    #-----头条视频播放器库，依赖自研播放器库，还包含系统播放器-----
    pod_binary 'TTVideo', '1.1.1'
    #-----视频重构基础库-----
    pod_binary 'TTVContainerScrollView', '0.1.2'
    pod_binary 'TTVTableViewItem', '0.1.0'
    pod_binary 'TTVTLIndexPathTools', '0.4.4'
    pod_binary 'TTVTableViewProtocolInterceptor', '0.1.2'

    #-----火山播放器 ----
    pod 'IESVideoPlayer', '0.1.16'
    pod_binary 'AWEVideoPlayer', '0.3.20'
    pod_binary 'Mantle','2.1.0-rc2'
    pod_binary 'CocoaLumberjack' , '3.4.2'
    

    #-----头条获取installID---
    pod_binary 'TTInstallService','2.1.6'

    #-----头条用户设置库--------
    pod_binary 'TTUserSettings','0.3.20'

    pod_binary 'TTRexxar', '0.8.14', subspecs:['Core', 'WebView', 'PackageApp', 'Plugins']
    #----头条组件协议库-----

    pod 'TTServiceProtocols','7.5.7.2'
    pod_binary 'BDTrackerProtocol','2.1.1'


    #-----头条头像-----
    pod 'TTAvatar','0.5.22'

    #-----头条加v认证工具-----
    pod 'TTVerifyKit','0.3.11.1-bugfix'
    pod 'BDMobileRuntime', '0.3.38'
    pod 'TTRegistry','7.4.0.3'

    #-----举报-----
    pod_binary 'TTReporter', '0.2.1'

    pod_binary 'TTAdSplashSDK', '0.4.4'
    pod_binary 'TTEntry', '0.1.7'

    #-----点赞分享顶踩不感兴趣----
    pod_binary 'TTBatchItemAction','0.1.8'

    #-----头条网络业务库------
    pod_binary 'TTNetBusiness','0.1.0', :subspecs => [
    'TTRouteSelectionManager',
    'DNSManager',
    'TTNetworkUtilities'
    ]

    #-----授权管理----
   # pod 'FHPushAuthorizationManager','0.1.4'
        pod 'FHPushAuthorizationManager', git:'git@code.byted.org:fproject/push_authorization_manager.git', :commit => '9e4474f01e3fd53497c4bfee294eaa030eb20335'

    #-----手机通讯录操作库---
    #pod_binary 'TTAddressBookService', '0.1.4'
    
    #-----头条基础库-----
    pod 'TTBaseLib','2.0.13', :subspecs => [
    'TTBaseTool',
    'TTBusinessManager',
    'TTCategory',
    'TTDeviceHelper',
    'TTLabelTextHelper',
    'TTSandBoxHelper',
    'TTUIResponderHelper',
    'TTNetworkHelper'
    ]
    pod_binary 'TTVersionHelper', '1.0.0'

    #-----头条主题库-----
    pod_binary 'TTThemed','0.1.36'

    #-----头条UI组件库-----
    pod 'TTUIWidget', git:'git@code.byted.org:TTIOS/tt_pods_ui.git', :commit => 'b9fc582c92fe8a0377676890beee95571a3ff737'
    
    pod 'Bytedancebase','1.4.0-rc.0', :subspecs => [
    'BDPlatformSDK',
    'BDDeprecatedSDK'
    ]
    pod 'ByteDanceKit', '2.1.0-rc.8', :subspecs => [
    'Foundation',
    'UIKit'
    ]
    #-----头条网络库-----
    pod_binary 'TTNetworkManager', '3.2.24.1'

    #-----播放器SDK相关-----
    pod 'TTPlayerSDK', '2.9.9.10'
    pod 'TTFFmpeg', '1.4.3'
    pod_binary 'TTVideoEngine', '1.9.3.24'
    pod 'TTPreloaderSDK', '1.4.20-rc.0'

    #-----头条sercive中间件-----
    pod_binary 'TTServiceKit', '0.4.1'
    #-----头条端监控库-----
    # pod_binary 'TTMonitor','0.7.9.58-rc.3' #这个版本还是有很多问题
    pod_binary 'MemoryGraphCapture', '1.2.4'
    pod_binary 'Heimdallr', '0.7.18-rc.7', :subspecs => [
    'Core',
    'Monitors',
    'TTMonitor',
    'HMDURLProtocolTracker', #
    'TTNet',
    'HMDStart',
    'Mach',
    'Utility',
    'DeviceInfo',
    'HMDANR',
    'HMDOOM',
    'CrashDetector',
    'CrashCapture',
    'Log',
    'UITracker',
#    'MemorySnapshot',
    'Upload',
    'HMDSession',
    'HMDConfig',
    'HMDStore',
    'ALog',
    'CloudCommand',
    'Network', #
    'HTTPRequestTracker', #
    'HMDOOMCrash', #
    'HMDWatchDog', #
    'Runloop',
    'UserException', #
    'MemoryGraph',
    'HMDDomestic',
    'Protect'
    ]
    pod_binary 'BDWatchdogProtector', '0.1.10'

    pod 'TTMacroManager','1.0.1'
    
    # pod_binary 'AWECloudCommand' , '1.0.7'
    pod_binary 'BDALog' , '0.1.12'
    pod 'BDAlogProtocol','0.1.7'

    #----- 长连接 & IM -----
    pod_binary 'TTLCSService','0.1.11' # 依赖于 'TTPushManager' 和 'TTReachability'
    pod_binary 'TTReachability','0.10.1'
    pod_binary 'Protobuf', '3.6.1.2'
    #----- 存储库 -----
    pod_binary 'TTPersistence', '0.2.3'
    pod_binary 'TTEntityBase', '0.2.4'
    #--- 图片库 --
    pod_binary 'TTImage', '0.8.4'
    pod_binary 'BDWebImage', '1.0.21',:subspecs => [
    'Core',
    'Decoder',
    'Download',
    'Download/Chromium',
    'Download/DownloadBase',
    'Download/URLSession',
    'SDAdapter',
    'Monitor'
    ]
    pod_binary 'MMKV', '1.0.23'

    pod_binary 'FLAnimatedImage' , '1.0.12'
    #-----头条交互式退出手势----
    pod_binary 'TTImagePreviewAnimateManager', '1.0.13'
    #-----头条日志库-----
    pod_binary 'TTTracker','1.3.20'
#    pod_binary 'BDTracker','1.3.1',:subspecs => [
#    'Network',
#    'Base',
#    'Core',
#    'Debug'
#    ]
    pod_binary 'BDDataDecorator','2.0.1',:subspecs => [
      'Data',
    ]
    
    pod 'Lynx','1.0.52',:subspecs =>[
    'Framework',
#    'InspectorFramework',
    'Native',
#    'InspectorNative',
    'JSRuntime',
    'ReleaseResource',
    'DebugResource']
    
    #-----头条推送SDK----
    pod 'BDUGPushSDK', '2.2.3'

    #-----路由-----
    pod 'TTRoute','1.1.3-rc.0-f100' # git:'git@code.byted.org:TTIOS/tt_pods_route.git', :branch => 'f100'

    #-----头条impression库-----
    pod_binary 'TTImpression', '0.0.26'
    #-----平台化基础库-----
    # pod 'TTPlatformBaseLib','1.3.1'
#    pod 'TTPlatformBaseLib'  , '0.2.29' , :subspecs => [
#    'TTProfileFillManager',
#    'TTTrackerWrapper',
#    'TTURLDomainHelper'
#    ]

    #----内测升级弹窗----
    pod_binary 'TTAppUpdateHelper', '1.0.9', :subspecs => [
    'TTUpdateHelper',
    'TTUpdateView'
    ]

    #-----TTAccountSDK-----
    pod 'TTAccountSDK', '5.10.1-rc.4', :subspecs => [
    'Account',
#    'Logger',
    'WeChatAccount',
    'OneKeyLogin',
    'ThirdPartyAccountFoundation',
    'TTAwemeAccount',
    'AppleAccount'
    ]
    pod 'BDUGContainer', '1.1.2'
    pod 'BDUGTrackerInterface', '1.1.1'
    pod 'BDUGMonitorInterface', '1.0.0'
    pod 'BDUGAccountOnekeyLogin', '1.1.8-rc.0'
    pod 'TYRZApiSDK' , '1.2.2-rc.0'
    pod 'EAccountApiSDK', '1.2.0-alpha.0'
    pod 'BDUGUnionSDK', '0.1.2'

    pod_binary 'BDUIKeyboardImplHook', '1.0.3'

    #************业务SDK**********

    pod_binary 'YYImage', '1.0.3'
    pod 'YYCache'
    pod_binary 'YYModel', '1.0.4'
    
    pod_binary 'YYWebImage', '1.0.4'
    pod_binary 'libwebp' , '0.6.1'
    pod_binary 'TTTAttributedLabel', '1.13.3'

    pod_binary 'JSONModel','1.7.0-private'
    # pod_binary 'Fabric','1.10.2'
    pod_binary 'MJExtension', '3.0.12'
    pod_binary 'MJRefresh' , '3.1.15.7'
    pod_binary 'KVOController', '1.2.0'
    pod_binary 'RSSwizzle', '0.1.1'
    pod_binary 'RNCryptor-objc', '3.0.5'
    pod_source 'OHHTTPStubs', '4.2.1', :configurations => ['Debug']
    pod_binary 'CHTCollectionViewWaterfallLayout', '0.9.5'
    pod_binary 'Aspects', '1.4.1'
    pod_binary 'SSZipArchive', '2.1.5'
    pod_binary 'libextobjc', '0.4.1'
    pod_binary 'ReactiveObjC', '3.0.0'
    pod_binary 'SDWebImage', '4.4.1', :subspecs => [
    'Core',
    'GIF',
    'WebP'
    ]
#    pod_binary 'BDAccountSessionSDK','0.1.11'
    pod_binary 'YYText' , '1.0.7'
    pod_source 'AMapLocation' , '2.6.0'
    pod_source 'AMap3DMap' , '6.9.0'
    pod_source 'AMapSearch'  , '6.9.0'
    pod_binary 'AMapFoundation' , '1.5.7'
    pod_binary 'OpenUDID', '0.1.0'
    
    #支持自动约束cell缓存高度
    pod_binary 'UITableView+FDTemplateLayoutCell', '1.6'

    #IMSDK升级，分支依赖方式
    pod 'lz4', '1.0.1'
    pod 'ByteRtcSDK', '2.6.13'
    pod 'TTIMSDK', :git => 'git@code.byted.org:im/TIMSDK.git', :branch => 'yang_branchf', :subspecs => [
        'IMKit_Default',
        'IMKit_WebSocket',
        'IMKit_Core',
        'Plugin_TTNetwork',
        'Foundation',
        'Feature_WebSocket',
        'Feature_EssentialPB',
        'Feature_Essential',
        'Feature_Core_Store',
        'Feature_Core_Sender',
        'Feature_Core_Puller',
        'Feature_Core_Notifier',
        'Feature_Core_Logger',
        'Feature_Core_ErrorHandler',
        'Feature_Core_CurrentUser',
        'Feature_Core_ConversationInfo',
        'Feature_Core_Config',
        'Feature_Core_Setting',
        'Feature_Core_ReadReceipt',
        'Feature_Core_Default',
        'Feature_Core_BroadCast',
        'Feature_ApplicationStatus',
        'IMSugar_MediaFileUploader',
        'IMSugar_RTCVideo',
        'Protocols',
        'Bridges'
    ]
    
    pod_binary 'IGListKit','3.4.0'
    pod_binary 'Bolts', '1.9.0'
    pod_binary 'ToutiaoFrontierWebSocket' , '0.2.5'
    # pod_binary 'WCDB', '1.0.7.5'
    pod_binary 'SQLiteRepairKit' , '1.2.1'
    pod_binary 'WCDBOptimizedSQLCipher' , '1.2.1'
    # pod_binary 'SocketRocket', '0.5.1'
    
    pod_binary 'TTFileUploadClient', '1.9.2.5'
    pod 'RXCollections' , '1.0'

    pod_binary 'MBProgressHUD' , '1.1.0'
    
    pod_binary 'Masonry' , '1.0.1'
    
    pod_binary 'Godzippa' , '1.1.0'
    
    pod_binary 'OpenSSL-Universal' , '1.0.1.20'
    
    pod        'boringssl' , '0.0.7'
    
    pod_binary 'AFNetworking' , '2.5.1'
    
    pod_binary 'FMDB','2.6.2',:subspecs => [
    'standard'
    ]
    pod_binary 'AFgzipRequestSerializer' , '0.0.2'
    
    # ab test sdk
    pod_binary  'BDABTestSDK', '1.0.2-rc.3'

    pod 'BDUGDeepLink', '1.1.1'
    
    pod_binary 'TTAppStoreStarManager', '1.0.12'

    pod_binary 'Quaterback', '1.0.2', :subspecs => [
    'Main/Core',
    'Main/News'
    ]
    
    pod_binary 'BDPainter', '1.0.0'
    
    # 开启依赖加速后需要指定依赖的库
    pod 'AWECloudCommand', '1.0.13'
    pod 'BDUGSecGuardInterface', '1.0.2.1-binary-debug'
    pod 'BDUGTuringInterface', '1.0.3.1-binary-debug'
    pod 'BDWCDB', '1.0.3'
#    pod_binary 'GoogleMaps', '3.1.0',:subspecs => [
#    'Base',
#    'Maps'
#    ]
    pod_binary 'SocketRocket', '0.5.1'
    pod 'TikTokOpenPlatformSDK', '3.0.0'
    pod 'objc-geohash', '0.0.3'
    pod 'protobuf_lite', '0.0.1'

    pod 'BDNativeWebComponent','0.1.0',:subspecs => [
        'Core',
        'Image'
#        'Video'
    ]
    
    pod_binary 'BDXElement', '1.0.0', :subspecs=> ['Core', 'ScrollView', 'ImpressionView']
end


def testPods
    pod 'BDSSOAuthSDK' ,  '1.1.1-alpha.6'
    
    pod_binary 'TTDebugAssistant', '0.2.33'
    pod_binary 'FLEX', '3.1.2'#, :configurations=>['Debug']
#    pod_source 'BDNetworkDevMonitor', '0.1.6'
    pod_binary 'TTSettingsManager/Debug'
    pod 'TTDebug' , :path => '../TTBundles/ios_tt_debug'
    pod_binary 'MLeaksFinder','1.0.3',:subspecs => [
    'Core'
    ]
    pod_binary 'FBRetainCycleDetector','0.1.5-alpha.3'
    pod 'LookinServer', :configurations => ['Debug']
#        pod 'FHErrorHubManager', :git => 'git@code.byted.org:fproject/FHErrorHubManager.git' , :commit => 'b04a60e50b4564346962b47d582f78eddc007408'
#    pod 'FHErrorHubManager', :path => '../../FHErrorHubManager'
    pod 'FHErrorHubManager', '1.0.12'
end

target 'NewsLiteInHouse' do
    testPods
    fhPods
    appPods
    appDevelopPods
    script_phase :name => 'sgmpreaction', :script => '${PODS_ROOT}/SecGuard/IESSafeGuardDev/Assets/Resources/sgmpre.sh', :execution_position  => :before_compile

end

target 'f100' do
#    testPods
  pod 'LookinServer', :configurations => ['Debug']
    fhPods
    appPods
    appDevelopPods
    script_phase :name => 'sgmpreaction', :script => '${PODS_ROOT}/SecGuard/IESSafeGuardDev/Assets/Resources/sgmpre.sh', :execution_position  => :before_compile
end

target 'serviceNofExtension' do
  pod 'BDUGPushSDK','2.2.3',:subspecs => [
  'Extension'
  ]
end

target 'com.f100.client.FHNotificationServiceExtension' do
  pod 'BDUGPushSDK','2.2.3',:subspecs => [
  'Extension'
  ]
end

# POD POST_INSTALL
post_install do |installer|

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Fix libstdc++.6在Xcode10编译报错问题

            # if target.name == "Pods-NewsLiteInHouse"
            #     xcconfig_path = config.base_configuration_reference.real_path
            #     xcconfig = File.read(xcconfig_path)
            #     new_xcconfig = xcconfig.sub('stdc++.6.0.9', 'c++')
            #     new_xcconfig = new_xcconfig.sub('stdc++.6', 'c++')

            #     File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
            # end
            # if target.name == "Pods-f100"
            #     xcconfig_path = config.base_configuration_reference.real_path
            #     xcconfig = File.read(xcconfig_path)
            #     new_xcconfig = xcconfig.sub('stdc++.6.0.9', 'c++')
            #     new_xcconfig = new_xcconfig.sub('stdc++.6', 'c++')

            #     File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
            # end
        end
        #账号
        if target.name == "TTAccountSDK"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'TTACCOUNT_OLD_SINAWEIBO_AUTH=1']
            end
        end
        target.build_configurations.each do |config|
            config.build_settings['WARNING_CFLAGS'] ||= ['$(inherited)', '-Wno-documentation']
        end

        #INHOUSE宏,生效条件为业务库：问答、视频等
        if target.name == "TTVideoService" || target.name == "TTWenda"  || target.name == "TTUGCFeature"|| target.name == "TTUGCFoundation"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','INHOUSE=1']
            end
        end
        if target.name == "TTDebug" || target.name == "TTAppRuntime"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','INHOUSE=1']
            end
        end
        if target.name == "TTArticleBase"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','SD_WEBP=1']
            end
        end
    end
    
    # 升级pod，解决framework头文件包含问题
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||=
          [
          '${PODS_ROOT}/AMap3DMap',
          '${PODS_ROOT}/AMapLocation',
          '${PODS_ROOT}/AMapSearch',
          '${PODS_ROOT}/AMapFoundation',
          '${PODS_ROOT}/BDTFactoryConfigurator',
          '${PODS_ROOT}/TYRZApiSDK/TYRZApiSDK/Classes',
          '${PODS_ROOT}/EAccountApiSDK/EAccountApiSDK/Classes',
          '${PODS_ROOT}/GoogleMaps/Maps/Frameworks',
          '${PODS_ROOT}/GoogleMaps/Base/Frameworks',
          '${PODS_ROOT}/BDUGUnionSDK/BDUGUnionSDK/Classes',
          '${PODS_ROOT}/TTNetBusiness/ios',
          '${PODS_ROOT}/TencentQQSDK/TencentQQSDK/Classes',
          '${PODS_ROOT}/Quaterback/BDDynamically/Frameworks/News/Release',
          '${PODS_ROOT}/ByteRtcSDK',
          ]
        end
    end
    
        
    # Xcode 11目前和CocoaPods有兼容问题，会导致Assets.car这个文件，由于出现在两处Output File而报错
    # 一处是Xcode自带的Copy Bundle Resources，一处是CocoaPods的[CP] Copy Pods Resources
    # 这个问题在Xcode 10上也有小概率发生，现在统一临时Fix下，参考CocoaPods/CocoaPods#8122
    installer.aggregate_targets.each do |target|
#        if ['Pods-f100', 'Pods-NewsLiteInHouse'].include?(target.name)
#            patched = false
#            target.user_targets.first.build_phases.each do |phase|
#                if phase.display_name == '[CP] Copy Pods Resources'
#                    assets_car_path = '${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/Assets.car'
#                    if !phase.input_paths
#                        phase.input_paths = []
#                    end
#                    if !phase.input_paths.include?(assets_car_path)
#                        phase.input_paths << assets_car_path
#                        patched = true
#                    end
#                end
#            end
#            target.user_project.save if patched
#        end
    end
end
