source 'git@code.byted.org:TTIOS/tt_pods_specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'TTFriendRelation' do
    pod 'TTFriendRelation', :path => '../../', :inhibit_warnings => false
    
    pod 'TTPushAuthorizationManager','0.1.3'
    pod 'TTNewsAccountBusiness'
    pod 'TTPlatformBaseLib', '0.2.9'
    pod 'TTNetworkManager', '2.2.1'
    pod 'TTPlatformUIModel', '0.2.24'
    pod 'TTThemed', '0.1.6'
    pod 'TTImagePicker', '1.1.5'
    pod 'Crashlytics', '3.7.2'
    pod 'TTEntry', '0.1.5'
    
end

