//
//  UIColor+TTVideo.h
//
//  Generated by Zeplin on 8/17/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (Player)

+ (UIColor *)ttv_C1_color;
+ (UIColor *)ttv_C2_color;
+ (UIColor *)ttv_C3_color;
+ (UIColor *)ttv_C4_color;
+ (UIColor *)ttv_C5_color;
+ (UIColor *)ttv_C6_color;
+ (UIColor *)ttv_C7_color;
+ (UIColor *)ttv_C8_color;
+ (UIColor *)ttv_C9_color;
+ (UIColor *)ttv_C10_color;

+ (UIColor *)tt_W1_color;
+ (UIColor *)tt_W2_color;
+ (UIColor *)tt_W3_color;
+ (UIColor *)tt_W4_color;
+ (UIColor *)tt_W5_color;
+ (UIColor *)tt_W6_color;
+ (UIColor *)tt_W7_color;

+ (UIColor *)tt_B1_color;
+ (UIColor *)tt_B2_color;

+ (UIColor *)tt_Y1_color;
+ (UIColor *)tt_Y2_color;
+ (UIColor *)tt_Y3_color;

+ (UIColor *)tt_R1_color;
+ (UIColor *)tt_R2_color;
@end
