//
//  UIColor+TTVideo.m
//
//  Generated by Zeplin on 8/17/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+TTVideo.h"

@implementation UIColor (Player)

#pragma mark C
+ (UIColor *)ttv_C1_color {
    return [UIColor colorWithWhite:0 alpha:1.f];
}

+ (UIColor *)ttv_C2_color {
    return [UIColor colorWithWhite:0 alpha:.87f];
}

+ (UIColor *)ttv_C3_color {
    return [UIColor colorWithWhite:0 alpha:.7f];
}

+ (UIColor *)ttv_C4_color {
    return [UIColor colorWithWhite:0 alpha:.54f];
}

+ (UIColor *)ttv_C5_color {
    return [UIColor colorWithWhite:0 alpha:.38f];
}

+ (UIColor *)ttv_C6_color {
    return [UIColor colorWithWhite:0 alpha:.26f];
}

+ (UIColor *)ttv_C7_color {
    return [UIColor colorWithWhite:0 alpha:.12f];
}

+ (UIColor *)ttv_C8_color {
    return [UIColor colorWithWhite:0 alpha:.08f];
}

+ (UIColor *)ttv_C9_color {
    return [UIColor colorWithWhite:0 alpha:.06f];
}

+ (UIColor *)ttv_C10_color {
    return [UIColor colorWithWhite:0 alpha:.04f];
}

#pragma mark W
+ (UIColor *)tt_W1_color {
    return [UIColor colorWithWhite:1 alpha:1.f];
}

+ (UIColor *)tt_W2_color {
    return [UIColor colorWithWhite:1 alpha:.96f];
}

+ (UIColor *)tt_W3_color {
    return [UIColor colorWithWhite:1 alpha:.9f];
}

+ (UIColor *)tt_W4_color {
    return [UIColor colorWithWhite:1 alpha:.7f];
}

+ (UIColor *)tt_W5_color {
    return [UIColor colorWithWhite:1 alpha:.5f];
}

+ (UIColor *)tt_W6_color {
    return [UIColor colorWithWhite:1 alpha:.3f];
}

+ (UIColor *)tt_W7_color {
    return [UIColor colorWithWhite:1 alpha:.1f];
}

#pragma mark B
+ (UIColor *)tt_B1_color {
    return [UIColor colorWithRed:30.f / 255.f green:136.f / 255.f blue:229.f / 255.f alpha:1.f];
}

+ (UIColor *)tt_B2_color {
    return [UIColor colorWithRed:3.0f / 255.0f green:75.0f / 255.0f blue:159.0f / 255.0f alpha:1.0f];
}

#pragma mark Y
+ (UIColor *)tt_Y1_color {
    return [UIColor colorWithRed:255.f / 255.f green:214.f / 255.f blue:0 alpha:1.f];
}

+ (UIColor *)tt_Y2_color {
    return [UIColor colorWithRed:255.f / 255.f green:149.f / 255.f blue:0 alpha:1.f];
}

+ (UIColor *)tt_Y3_color {
    return [UIColor colorWithRed:255.f / 255.f green:116.f / 255.f blue:42.f / 255.f alpha:1.f];
}

#pragma mark R
+ (UIColor *)tt_R1_color {
    return [UIColor colorWithRed:1 green:0 blue:0 alpha:1.f];
}

+ (UIColor *)tt_R2_color {
    return [UIColor colorWithRed:255.f / 255.f green:53.f / 255.f blue:141.f / 255.f alpha:1.f];
}

@end
