# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do |options|
    ENV["FASTLANE_PASSWORD"] = options[:itc_password]
    # add actions here: https://docs.fastlane.tools/actions
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    sh "rm -rf #{options[:output_directory]}"
    increment_build_number_in_plist(
      scheme: "NewsInHouse",
      build_number: options[:build_number]
    )
    version = get_version_number_from_plist(scheme: "NewsInHouse")
    build = get_build_number_from_plist(scheme: "NewsInHouse")
    #build_app(scheme: "NewsInHouse",
#              workspace: "Article.xcworkspace")
    gym(
      scheme: "NewsInHouse",
      clean: true,
      silent: true,
      output_directory: options[:output_directory],
      output_name: "F100_#{version}_#{build}"
    )
  end
end
