#use_frameworks!
source 'git@code.byted.org:TTIOS/tt_pods_specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'TTPlatformBaseLib_Example' do
  pod 'TTPlatformBaseLib', :path => '../'
  pod 'TTNetworkManager', '2.1.1'
  pod 'TTTracker', '0.9.2.1'
  pod 'TTBaseLib'
  pod 'TTImagePicker'
  pod 'Crashlytics', '3.7.2'
  pod 'TTNewsAccountBusiness'
  pod 'TTAccountSDK'
  pod 'TTPlatformUIModel'
  target 'TTPlatformBaseLib_Tests' do
    inherit! :search_paths

    
  end
end
