source 'git@code.byted.org:TTIOS/tt_pods_specs.git'
source 'git@code.byted.org:TTIOS/cocoapods-master-specs-mirror.git'

use_frameworks!

target 'TTDiggButton_Example' do
  pod 'TTDiggButton', :path => '../'
  pod 'TTNetworkManager', '2.2.8.11'
  pod 'SDWebImage'
  pod 'SDWebImage/Core'
  pod 'SDWebImage/WebP'


  target 'TTDiggButton_Tests' do
    inherit! :search_paths

    
  end
end
