source 'git@code.byted.org:TTIOS/tt_pods_specs.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

##to avoid crashlytics pod update error
#pre_install do |installer|
#    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
#    def installer.verify_no_static_framework_transitive_dependencies; end
#end

target 'TTUIWidget_Example' do
    pod 'TTUIWidget', :path => '../'
    pod 'TTInstallService', '1.0.0.6'
    pod 'TTNetworkManager', '2.2.8.11'
end
