#use_frameworks!

source 'git@code.byted.org:TTIOS/tt_pods_specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'TTAdModule_Example' do
  pod 'TTAdModule', :path => '../'
  pod 'TTNetworkManager', '2.1.0'
  pod 'TTInstallService', '1.0.0'
  pod 'TTTracker', '1.0.0'
  pod 'TTPersistence'
  pod 'TTPlatformBaseLib'
  pod 'TTPlatformUIModel'
  pod 'TTNetBusiness'
  pod 'TTImagePicker'
  pod 'TTAccountSDK'
  pod 'TTNewsAccountBusiness'
  pod 'Crashlytics', '3.7.2'
  target 'TTAdModule_Tests' do
    inherit! :search_paths

    
  end
end
