source 'git@code.byted.org:iOS_Library/publicthird_binary_repo.git'
source 'git@code.byted.org:iOS_Library/publicthird_source_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_binary_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_source_repo.git'
source 'git@code.byted.org:iOS_Library/toutiao_binary_repo.git'
source 'git@code.byted.org:iOS_Library/toutiao_source_repo.git'
source 'git@code.byted.org:TTVideo/ttvideo-pods.git'
source 'git@code.byted.org:ugc/UGCSpecs.git'

target 'FHCommonUI_Example' do
  pod 'FHCommonUI', :path => '../'

  target 'FHCommonUI_Tests' do
    inherit! :search_paths

    
  #summary -> 头条iOS通用基础图片库 
  pod 'BDWebImage', '0.2.8'
  
  end
end
