#use_frameworks!
source 'git@code.byted.org:TTIOS/tt_pods_specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'TTPhotoScrollVC_Example' do
  pod 'TTPhotoScrollVC', :path => '../'
  pod 'TTBaseLib', '1.0.9'
  pod 'TTUIWidget', git: 'git@code.byted.org:TTIOS/tt_pods_ui.git', branch: 'dev_sd4'
  pod 'TTImage', git: 'git@code.byted.org:TTIOS/tt_pods_image.git', branch: 'dev_sd4'
  pod 'TTImagePicker', git:'git@code.byted.org:TTIOS/tt_pods_image_picker.git', :branch => 'master'
  pod 'TTServiceProtocols', git:'git@code.byted.org:TTIOS/tt_pods_service_protocols.git', :branch => 'develop'
  pod 'TTNetworkManager', '2.1.0'
  target 'TTPhotoScrollVC_Tests' do
    inherit! :search_paths

    
  end
end
