source 'git@code.byted.org:iOS_Library/publicthird_binary_repo.git'
source 'git@code.byted.org:iOS_Library/publicthird_source_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_binary_repo.git'
source 'git@code.byted.org:iOS_Library/privatethird_source_repo.git'
source 'git@code.byted.org:iOS_Library/toutiao_binary_repo.git'
source 'git@code.byted.org:iOS_Library/toutiao_source_repo.git'
source 'git@code.byted.org:TTVideo/ttvideo-pods.git'
source 'git@code.byted.org:ugc/UGCSpecs.git'

target 'FHHouseTrend_Example' do
  pod 'FHHouseTrend', :path => '../'

  target 'FHHouseTrend_Tests' do
    inherit! :search_paths

    
  #summary -> 获取用户首次安装后的一些信息，如installID、deviceID 
  pod 'TTInstallService', '1.0.0.6'
  
  end
end
